services:
  db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: OrderInvoiceDb
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d OrderInvoiceDb"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbit:
    image: rabbitmq:3.13-management
    container_name: order-rabbit
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  orderapi:
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    container_name: order-api
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=OrderInvoiceDb;Username=postgres;Password=password"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      Rabbit__Host: "rabbit"
      Rabbit__User: "admin"
      Rabbit__Pass: "admin"
      Rabbit__Port: "5672"
      Rabbit__Exchange: "order-ex"
      Rabbit__RoutingKey: "order.created"
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  worker:
    build:
      context: .
      dockerfile: OrderService.OutboxWorker/Dockerfile
    container_name: order-worker
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=OrderInvoiceDb;Username=postgres;Password=password"
      Rabbit__Host: "rabbit"
      Rabbit__User: "admin"
      Rabbit__Pass: "admin"
      Rabbit__Port: "5672"
      Rabbit__VirtualHost: "/"
      Rabbit__Exchange: "order-ex"
      Rabbit__RoutingKey: "order.created"
      Rabbit__Queue: "q-order-created"
      Invoice__SimulatedLatencyMs: "400"
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      orderapi:
        condition: service_healthy
    restart: unless-stopped

volumes:
  dbdata: